/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "ulog/ulog_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ulog_pb_va_arg, ulog_pb_va_arg, AUTO)


PB_BIND(ulog_pb_message, ulog_pb_message, AUTO)



