/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_ULOG_PB_SRC_ULOG_MESSAGE_PB_H_INCLUDED
#define PB_ULOG_PB_SRC_ULOG_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ulog_pb_message {
    uint32_t tag;
    pb_callback_t va_list;
} ulog_pb_message;

typedef struct _ulog_pb_va_arg {
    int32_t id;
    pb_callback_t value;
} ulog_pb_va_arg;


/* Initializer values for message structs */
#define ulog_pb_va_arg_init_default              {0, {{NULL}, NULL}}
#define ulog_pb_message_init_default             {0, {{NULL}, NULL}}
#define ulog_pb_va_arg_init_zero                 {0, {{NULL}, NULL}}
#define ulog_pb_message_init_zero                {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ulog_pb_message_tag_tag                  1
#define ulog_pb_message_va_list_tag              2
#define ulog_pb_va_arg_id_tag                    1
#define ulog_pb_va_arg_value_tag                 2

/* Struct field encoding specification for nanopb */
#define ulog_pb_va_arg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    id,                1) \
X(a, CALLBACK, REQUIRED, BYTES,    value,             2)
#define ulog_pb_va_arg_CALLBACK pb_default_field_callback
#define ulog_pb_va_arg_DEFAULT NULL

#define ulog_pb_message_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   tag,               1) \
X(a, CALLBACK, REPEATED, MESSAGE,  va_list,           2)
#define ulog_pb_message_CALLBACK pb_default_field_callback
#define ulog_pb_message_DEFAULT NULL
#define ulog_pb_message_va_list_MSGTYPE ulog_pb_va_arg

extern const pb_msgdesc_t ulog_pb_va_arg_msg;
extern const pb_msgdesc_t ulog_pb_message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ulog_pb_va_arg_fields &ulog_pb_va_arg_msg
#define ulog_pb_message_fields &ulog_pb_message_msg

/* Maximum encoded size of messages (where known) */
/* ulog_pb_va_arg_size depends on runtime parameters */
/* ulog_pb_message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
